apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-servicemonitor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Prashantkumar477447/Node.js-Application.git
    targetRevision: HEAD
    path: app/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
